Updated `Docs` link for `create-web3-dapp` in Readme.md  (#56)
alchemyplatform/create-web3-dapp pull request #62
Opened 2023-02-22 14:59 UTC by adityakode

Docs Link for [Docs](https://docs.alchemy.com/create-web3-dapp) – How to develop apps bootstrapped with Create Web3 Dapp 
was broken which resulted in 404 error . Fixed by updating it to https://www.alchemy.com/dapps/create-web3-dapp.
Fixed error #56

2023-02-22 15:02 UTC, adityakode commented
@Eversmile12  @thatguyintech  ps review

2023-03-08 17:43 UTC, xscottxbrownx requested changes
I believe this is the intended link from the start honestly: https://docs.alchemy.com/docs/create-web3-dapp

2023-03-08 17:44 UTC, xscottxbrownx commented
@Eversmile12 I think this would be a better link: https://docs.alchemy.com/docs/create-web3-dapp

AND actually seems to be the intended link from the start honestly.

2023-03-08 17:58 UTC, xscottxbrownx requested changes
I believe this is the intended link from the start honestly: https://docs.alchemy.com/docs/create-web3-dapp

2023-03-09 02:40 UTC, adityakode commented
yes. 
in the Readme, the given link is https://docs.alchemy.com/create-web3-dapp, which is broken
but the working link, provided in an earlier comment by @xscottxbrownx, is https://docs.alchemy.com/docs/create-web3-dapp

2023-03-09 02:44 UTC, adityakode commented
@xscottxbrownx  I have changed the link.

2025-02-10 21:18 UTC, Dan-Nolan commented
Thank you for opening up this PR! 

We just put out a new release #124 which is a big change from the previous version and will make use of [Scaffold-Alchemy](https://github.com/alchemyplatform/scaffold-alchemy). Check it out when you have the chance 😄

2025-02-10 21:18 UTC, closed without merging